### PR TITLE
Update pavucontrol-qt.desktop.in

### PR DESCRIPTION
**Pull request by smarquespt**

### CODE REVIEW

**Comment by palinek** [comment]
I think, we should use here the same method for .desktop localization as in other LXQt projects (separate \*\__lang_.desktop translation files)...

@lxde/lxqt ?

**Comment by luis-pereira** [comment]
I agree with @palinek

**Comment by smarquespt** [comment]
Will do.

**Comment by smarquespt** [comment]
Please check if https://github.com/lxde/pavucontrol-qt/pull/21/commits/9e60db4a300392db7e7064e5b7f90446ca7b1721 is ok.

**Pull request closed without merging**
